### ISSUE TITLE
current conditions label and owntitle

### ISSUE THREAD

**Issue by 73cirdan** [mykle1/MMM-BMW-DS#1]
When adding an owntitle to the config.js and entering the currenly part of the getdom for the topline the owntitle is not used. It states "Current conditions" hard coded in the .js
It would work if i would go into the minutly part, but I don't understand when minutly is filled

**Comment by mykle1** [comment]
You were right. It was hard coded. I have fixed it and uploaded the file to the repo. Thanks for pointing that out to me.
