### ISSUE TITLE
No new API's

### ISSUE THREAD

**Issue by Rayvenhaus** [mykle1/MMM-BMW-DS#10]
As of the 1sy of Aug, 2020, darksky.net has joined apple and is no longer accepting new API requests and, therefore, are no longer issuing new API keys, making this module unusable by new users such as myself.  :(

[https://blog.darksky.net/]

**Comment by mykle1** [comment]
Yes. I've known about this for some time. Nothing I can do about that. I have other weather modules, similar in appearance and function that use different providers, not to mention all the other weather modules available to you
