### ISSUE TITLE
Icons are showing 1/2 size no matter what CCS (1-6) is used.

### ISSUE THREAD

**Issue by JohnWPB** [mykle1/MMM-BMW-DS#3]
First, thank you for the re-write.  A shame Weather Underground went the way of the Weather Chanel.

Anyhow, I your installed your module, and it looks fantastic!  Exactly what I was looking for, bottom of the screen & intrusive.   However the icons appear to be showing half the size as intended, and even on a 42" screen, there is no way to tell what the icons actually are.
Not sure what all you need as fat as info, its a RasPi 3b+, latest MM and Raspian installs and all up to date as of 3 days ago.
Thanks again!
   - John

**Comment by JohnWPB** [comment]
Interesting, I dragged the image to the edit window from my desktop, AND clicked and browsed for the screen shot to attach it, and neither way seemed to work.  Anyhow I uploaded it to PostImage.org, and you can see it there:
https://i.postimg.cc/sxGrbLfs/Magic-Mirror-SS.jpg

**Comment by mykle1** [comment]
Please add this to your custom.css file and adjust accordingly. Only make one change at a time so that you can see the changes and understand what each does. In your case, start with the image element and adjust width and height to the same percentage. If you don't need to change anything else, don't. Try width and height at 2.75% to start and see how it looks then go from there.

```
.MMM-BMW-DS .header {
  color: yellow;               /* Header color. */
}
.MMM-BMW-DS .image {              /* icon size */
   width: 1.75%;
   height: 1.75%;
   margin-top: 0px;
   margin-bottom: -10px;
}

.MMM-BMW-DS .current {
  color: #FFFFFF;               /* Current text forecast color. Default is white. */
  font-family: Muli;
/*  font-size: .6em; */
}

.MMM-BMW-DS .summary {
  color: #FFFFFF;               /* General summary text forecast color. Default is white. */
  font-family: Muli;
/*  font-size: .5em;  */
   display: none;           /* uncomment to hide */
}

.MMM-BMW-DS .daily {
  color: #FFFFFF;               /* Days of the week and hi/lo temp color. Default is white. */
  font-family: Muli;
/*  font-size: .6em; */
}
```

**Comment by JohnWPB** [comment]
Sorry for the delay in responding.  Thank you for the tips, I will follow up and try that out when I get back home in a couple weeks.   Thanks again!
