### ISSUE TITLE
Customizing # of days

### ISSUE THREAD

**Issue by bpennypacker** [mykle1/MMM-BMW-DS#4]
Any chance of adding a parameter to specify the number of days to display instead of displaying all 7 days? I only have space to display 5 days so I've just commented out the appropriate lines from the module. Would be nice if that could just be a parameter instead...

**Comment by mykle1** [comment]
I'm pretty busy these days with newer MM projects so it's unlikely I'll get around to that. However, you can make those changes and submit a pull request and I'll approve it. Thanks for your interest in the module. :-)
