### ISSUE TITLE
Won’t go on the bottom bar

### ISSUE THREAD

**Issue by iamhollis84** [mykle1/MMM-BMW-DS#6]
No matter what I do, the module stays in the middle
![image](https://user-images.githubusercontent.com/38348232/77675951-0a649c80-6f64-11ea-8994-f4589507586b.jpg)

**Comment by mykle1** [comment]
position: "bottom_bar", is set in your config entry? It is the default. If you need help please move this conversation to the MagicMirror forum. Post a topic in troubleshooting and I will be happy to help you there.
