### ISSUE TITLE
Dark Sky no longer accepting new signup's

### ISSUE THREAD

**Issue by MadMooJuice** [mykle1/MMM-BMW-DS#7]
Not able to get an API to run this module, as Dark Sky has suspended acceptance of new signups.

**Comment by mykle1** [comment]
There's nothing I can do about that, sir. When and/if darksky suspends or invalidates current working api keys I will find another api and rewrite the module. I don't have plans to do so before then. Feel free to fork the repo and make any changes you like. If you're going to submit an PR then please don't changes the display if you want me to accept the PR. Thanks.

**Comment by mykle1** [comment]
I moved to another api

https://forum.magicmirror.builders/topic/12691/www-bmw-cc
