### ISSUE TITLE
Current day's high/lows 

### ISSUE THREAD

**Issue by humdinger44** [mykle1/MMM-BMW-DS#8]
Hi. Love the module and I've been using it for a long time. My only complaint is that the forecast section starts with tomorrow. There is no information displayed for the current day's high/low, just the current conditions. If it is 75 degs at 10 am, is it going to stay at 75 all day or is the high 95? I have to go elsewhere to figure that out or try to remember what the module said yesterday.

Cheers

**Comment by humdinger44** [comment]
in mmm-bmw-ds.js there are two sections that look like this

            moment.unix(forecast.daily.data[0].time).local().format('ddd') + " &nbsp" + "<img class = image src=./modules/MMM-BMW-DS/icons/" + forecast.daily.data[0].icon + ".png>" + " &nbsp" + Math.round(forecast.daily.data[0].temperatureHigh) + "/" + Math.round(forecast.daily.data[0].temperatureLow) + " &nbsp &nbsp  &nbsp &nbsp &nbsp" +

for both sections, taking all the numbers in brackets and lowering them by 1 ( [1] -> [0] )starts the forecast at the current day!

**Comment by mykle1** [comment]
> in mmm-bmw-ds.js there are two sections that look like this
> 
> ```
>         moment.unix(forecast.daily.data[0].time).local().format('ddd') + " &nbsp" + "<img class = image src=./modules/MMM-BMW-DS/icons/" + forecast.daily.data[0].icon + ".png>" + " &nbsp" + Math.round(forecast.daily.data[0].temperatureHigh) + "/" + Math.round(forecast.daily.data[0].temperatureLow) + " &nbsp &nbsp  &nbsp &nbsp &nbsp" +
> ```
> 
> for both sections, taking all the numbers in brackets and lowering them by 1 ( [1] -> [0] )starts the forecast at the current day!

Done. You could send a PR next time haha
